<?php

namespace SenseiTarzan\CustomCrops\Item;


use SenseiTarzan\SymplyPlugin\behavior\items\builder\ItemBuilder;
use SenseiTarzan\SymplyPlugin\behavior\items\Food;

class EggPlant extends Food
{
	public function getFoodRestore(): int
	{
		return 2;
	}

	public function getSaturationRestore(): float
	{
		return 0.5;
	}

	public function getItemBuilder(): ItemBuilder
	{
		return parent::getItemBuilder()
			->setIcon("eggplant"); // TODO: Change the autogenerated stub
	}
}